FROM golang:1.16.3-alpine3.13

WORKDIR /workspaces/200-colony-movie-night-bot

Run go get -v golang.org/x/tools/gopls
Run go get -v github.com/go-delve/delve/cmd/dlv
Run go get -v github.com/ramya-rao-a/go-outline