FROM golang:1.16.3-alpine3.13 as devtools

RUN apk update \
    && apk add g++ make \
    # Go dev tools
    && go get -v golang.org/x/tools/gopls & \
    go get -v github.com/go-delve/delve/cmd/dlv & \
    go get -v github.com/ramya-rao-a/go-outline & \
    go get -v golang.org/x/lint/golint & \
    go get -v golang.org/x/tools/refactor/rename & \
    go get -v github.com/godoctor/godoctor & \
    go get -v honnef.co/go/tools/cmd/staticcheck & \
    wait

FROM devtools

ENV GOPATH=/home/golang/go
ENV CGO_ENABLED=1

RUN apk update && apk add \
    bash \ 
    shadow \
    sqlite  \
    python3 \
    nodejs \
    npm \
    && ln -sf python3 /usr/bin/python \
    && groupadd -g 1000 docker \
    && useradd -u 1000 -ms /bin/bash -g docker golang

WORKDIR /home/golang
COPY --chown=golang:docker . /home/golang

USER golang

VOLUME /home/golang