FROM golang:1.16.3-alpine3.13

ENV CGO_ENABLED=1

COPY . .

RUN apk update
RUN apk add sqlite

# Packages needed for setting up VS Code SQL extensions
RUN apk add g++ make python3 nodejs npm
RUN ln -sf python3 /usr/bin/python

RUN go get -v golang.org/x/tools/gopls
RUN go get -v github.com/go-delve/delve/cmd/dlv
RUN go get -v github.com/ramya-rao-a/go-outline
RUN go get -v golang.org/x/lint/golint
RUN go get -v golang.org/x/tools/refactor/rename
RUN go get -v github.com/godoctor/godoctor
RUN go get -v honnef.co/go/tools/cmd/staticcheck

RUN cd cli && go mod tidy
RUN cd bot && go mod tidy